#!/usr/bin/env node
/* =====================================================================
   Landing page generator. Runs on every Vercel deploy (see vercel.json).

   Reads every campaign in landing-pages/campaigns/*.js, renders it with the
   shared shell below plus its offer (offers/<OFFER>.js), and writes
   /lp/<slug>-<offer suffix>.html. vercel.json rewrites the clean URL
   /<slug>-equity-compensation-webinar to that file.

   No dependencies. Run locally with:  node landing-pages/build.js
   ===================================================================== */
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'lp');
const shared = require('./shared');
const css = fs.readFileSync(path.join(__dirname, 'lp.css'), 'utf8').replace(/\/\*[\s\S]*?\*\//g, '').replace(/\n\s*/g, '');
const js = fs.readFileSync(path.join(__dirname, 'lp.js'), 'utf8');

const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const slugify = (s) => String(s).toLowerCase().normalize('NFKD').replace(/[̀-ͯ]/g, '').replace(/&/g, ' and ').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');

// Every possible form field. Offers pick from this list, in order.
const FIELDS = {
  name:     (c) => ({ id: 'name', label: 'Full name', type: 'text', auto: 'name' }),
  email:    (c) => ({ id: 'email', label: 'Email', type: 'email', auto: 'email' }),
  phone:    (c) => ({ id: 'phone', label: 'Phone', type: 'tel', auto: 'tel' }),
  employer: (c) => ({ id: 'employer', label: 'Employer', type: 'text', auto: 'organization', value: c.COMPANY_NAME }),
};

const LOGO_SVG = `<svg class="brand-mark" viewBox="0 0 80 80" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><g transform="translate(40 40)">${
  [0, 60, 120, 180, 240, 300].map((r, i) => `<g transform="rotate(${r})"><path d="M-9 -26 L0 -16 L9 -26" stroke="${i % 2 ? '#33CCFF' : '#0099FF'}" stroke-width="3.5" fill="none" stroke-linecap="round" stroke-linejoin="round"/></g>`).join('')
}</g></svg>`;

function render(c, offer) {
  const S = shared.SPEAKER;
  const url = `https://skyviewfg.com/${c.slug}-${offer.urlSuffix}`;
  const campaignId = `${c.slug}-${offer.urlSuffix}`;
  const agenda = offer.agenda ? offer.agenda(c) : [];

  const fieldsHtml = offer.fields.map((k) => {
    const f = FIELDS[k](c);
    return `<div class="form-field"><label for="${f.id}">${f.label}</label><input type="${f.type}" id="${f.id}" name="${f.id}" required autocomplete="${f.auto}"${f.value ? ` value="${esc(f.value)}"` : ''}></div>`;
  }).join('\n            ');

  const sessionsHtml = offer.showSessions ? `
          <fieldset class="sessions">
            <legend>Choose a session</legend>
            ${c.SESSIONS.map((s, i) => `<label class="session"><input type="radio" name="session" value="${esc(s)}" required><span class="when"><span class="day">${esc(s.split(' · ')[0])}</span>${s.includes(' · ') ? `<span class="time">${esc(s.split(' · ').slice(1).join(' · '))}</span>` : ''}</span></label>`).join('\n            ')}
          </fieldset>` : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- GENERATED by landing-pages/build.js from landing-pages/campaigns/${esc(c.file)}. Do not edit this file; edit the campaign config. -->
<!-- Google Analytics (GA4) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=${shared.GA4_ID}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', '${shared.GA4_ID}', { content_group: 'landing-page', campaign_slug: '${campaignId}' });
</script>
<title>${esc(offer.title(c))}</title>
<meta name="description" content="${esc(offer.description(c))}">
<meta name="robots" content="noindex, follow">
<link rel="canonical" href="${url}">
<meta property="og:type" content="website">
<meta property="og:url" content="${url}">
<meta property="og:title" content="${esc(offer.title(c))}">
<meta property="og:description" content="${esc(offer.description(c))}">
<meta property="og:image" content="https://skyviewfg.com/assets/og-image.jpg">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta name="twitter:card" content="summary_large_image">
<link rel="icon" type="image/svg+xml" href="/favicon.svg">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;1,400&family=Manrope:wght@400;600;700&family=JetBrains+Mono:wght@400&display=swap" rel="stylesheet">
<style>${css}</style>
</head>
<body>

<header class="lp-hero">
  <div class="container">
    <div class="brand" aria-label="Skyview Financial Group">
      ${LOGO_SVG}
      <span class="brand-text"><span class="brand-name">Skyview</span><span class="brand-sub">Financial Group</span><span class="brand-tag">Registered Investment Advisor</span></span>
    </div>
    <span class="eyebrow">${esc(offer.eyebrow)}</span>
    <h1>${offer.headline(c, esc)}</h1>
    <p class="lead">${esc(offer.lead)}</p>
    <a href="#register" class="btn btn--primary">${esc(offer.heroCta)} <span class="arrow">→</span></a>
  </div>
</header>

<main class="lp-main">
  <div class="container lp-grid">
    <div class="lp-content">
      ${agenda.length ? `<section class="lp-section" aria-labelledby="agenda-h">
        <span class="eyebrow">Agenda</span>
        <h2 id="agenda-h">${esc(offer.agendaTitle)}</h2>
        <ol class="agenda">
          ${agenda.map((a, i) => `<li><span class="num">0${i + 1}</span><p>${esc(a)}</p></li>`).join('\n          ')}
        </ol>
      </section>` : ''}
      <section class="lp-section" aria-labelledby="speaker-h">
        <span class="eyebrow">Your presenter</span>
        <div class="speaker">
          <img src="${S.photo}" width="140" height="196" alt="${esc(S.name)}" loading="lazy" decoding="async">
          <div>
            <h3 class="name" id="speaker-h">${esc(S.name)}<span class="creds">${esc(S.credentials)}</span></h3>
            <p class="role">${esc(S.title)}</p>
            <p class="bio">${esc(S.bio)}</p>
          </div>
        </div>
      </section>
    </div>

    <aside class="lp-aside">
      <div class="lp-form" id="register" data-lp-form data-fallback-email="${esc(shared.FALLBACK_EMAIL)}">
        <div class="form-head">
          <span class="eyebrow">Register</span>
          <h2>${esc(offer.formTitle)}</h2>
          <p class="sub">${esc(offer.formSub)}</p>
        </div>
        <form action="https://formspree.io/f/${esc(c.FORMSPREE_ID)}" method="POST" data-offer="${esc(c.OFFER)}">
          ${sessionsHtml}
            ${fieldsHtml}

          <input type="hidden" name="campaign" value="${esc(campaignId)}">
          <input type="hidden" name="source" value="">
          <input type="hidden" name="_subject" value="${esc(offer.subject(c))}">

          <div class="form-honeypot" aria-hidden="true">
            <label for="website_url">Website</label>
            <input type="text" id="website_url" name="website_url" tabindex="-1" autocomplete="off">
            <label for="_gotcha">Confirm</label>
            <input type="text" id="_gotcha" name="_gotcha" tabindex="-1" autocomplete="off">
          </div>

          <div class="cf-turnstile" data-sitekey="${shared.TURNSTILE_SITEKEY}" data-theme="light" data-size="flexible" data-appearance="interaction-only"></div>

          <button type="submit" class="btn btn--primary form-submit">${esc(offer.submitLabel)} <span class="arrow">→</span></button>
          <p class="form-disclaimer">By registering, you agree that Skyview Financial Group may contact you by email or phone about this event. See our <a href="/disclaimers.html" target="_blank" rel="noopener">Privacy Policy</a>. Please do not include sensitive financial account information.</p>
          <p class="form-status" data-form-status role="alert"></p>
        </form>
        <div class="form-success" aria-live="polite">
          <div class="check" aria-hidden="true">✓</div>
          <h2>${esc(offer.successTitle)}</h2>
          ${offer.successBody(c, esc)}
        </div>
      </div>
    </aside>
  </div>
</main>

<section class="trust" aria-label="About Skyview Financial Group">
  <div class="container">
    <ul>${shared.TRUST.map((t) => `<li>${esc(t)}</li>`).join('')}</ul>
  </div>
</section>

<footer class="lp-disclosure">
  <div class="container">
    <p class="sponsor">Sponsored solely by Skyview Financial Group, LLC. Not affiliated with, endorsed by, or sponsored by ${esc(c.COMPANY_NAME)}.</p>
    <p>This presentation is educational and is not individualized advice. Skyview Financial Group does not prepare or file tax returns.</p>
    ${shared.SEC_DISCLOSURE.map((p) => `<p>${esc(p)}</p>`).join('\n    ')}
    <p class="copy">© ${new Date().getFullYear()} Skyview Financial Group, LLC. All rights reserved.</p>
  </div>
</footer>

<script>${js}</script>
<script src="https://challenges.cloudflare.com/turnstile/v0/api.js" async defer></script>
</body>
</html>
`;
}

// ---------------------------------------------------------------------
function build() {
  const dir = path.join(__dirname, 'campaigns');
  const files = fs.readdirSync(dir).filter((f) => f.endsWith('.js') && !f.startsWith('_'));
  fs.rmSync(OUT, { recursive: true, force: true });
  fs.mkdirSync(OUT, { recursive: true });

  const seen = new Set();
  for (const file of files) {
    const c = { ...require(path.join(dir, file)), file };
    const need = ['COMPANY_NAME', 'TICKER', 'OFFER', 'FORMSPREE_ID'];
    for (const k of need) if (!c[k]) throw new Error(`${file}: missing ${k}`);
    const offerPath = path.join(__dirname, 'offers', `${c.OFFER}.js`);
    if (!fs.existsSync(offerPath)) throw new Error(`${file}: unknown OFFER "${c.OFFER}"`);
    const offer = require(offerPath);
    if (offer.showSessions && !(Array.isArray(c.SESSIONS) && c.SESSIONS.length)) throw new Error(`${file}: SESSIONS required for ${c.OFFER}`);

    c.slug = c.SLUG || slugify(c.COMPANY_NAME);
    const name = `${c.slug}-${offer.urlSuffix}`;
    if (seen.has(name)) throw new Error(`${file}: duplicate page ${name}`);
    seen.add(name);

    fs.writeFileSync(path.join(OUT, `${name}.html`), render(c, offer));
    console.log(`  built /${name}  <- campaigns/${file}`);
  }
  console.log(`Landing pages: ${seen.size} built.`);
}

build();
